package com.seniorlink.app
import android.Manifest
import android.app.*
import android.content.*
import android.content.pm.PackageManager
import android.location.LocationManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.*

private val Blue=Color(0xFF0B5CAA); private val Teal=Color(0xFF0AA88F); private val Bg=Color(0xFFF6FAFC); private val Ink=Color(0xFF18324A); private val Red=Color(0xFFE74747)
private const val PREF="seniorlink"
enum class S { SPLASH,O1,O2,O3,LOGIN,CADASTRO,WELCOME,HOME,PERFIL,LOCAL,LEMBRETES,NOVO,SOS,APRENDER,DETALHE,CONTATOS,CONFIG }
data class Contact(val id:Long,val name:String,val phone:String,val relation:String)
data class Reminder(val id:Int,val title:String,val desc:String,val time:Long,val repeat:String,val active:Boolean)
data class Profile(val name:String="Maria Silva de Oliveira",val birth:String="12/03/1950",val blood:String="O+",val allergies:String="Dipirona",val meds:String="Pressão alta, Vitamina D",val conditions:String="Hipertensão, Diabetes tipo 2")
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}

@Composable fun App(){
 val c=LocalContext.current; val p=remember{c.getSharedPreferences(PREF,0)}
 var s by remember{mutableStateOf(if(p.getBoolean("logged",false))S.HOME else S.SPLASH)}
 var profile by remember{mutableStateOf(loadProfile(p))}
 val contacts=remember{mutableStateListOf<Contact>().apply{addAll(loadContacts(p))}}
 val reminders=remember{mutableStateListOf<Reminder>().apply{addAll(loadReminders(p))}}
 var big by remember{mutableStateOf(p.getBoolean("big",false))}
 val location=rememberLauncherForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){}
 val notify=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){}
 fun go(x:S){s=x}
 BackHandler(s!=S.HOME&&s!=S.SPLASH){s=S.HOME}
 MaterialTheme(colorScheme=lightColorScheme(primary=Blue,secondary=Teal,background=Bg,error=Red),typography=Typography(bodyLarge=Typography().bodyLarge.copy(fontSize=if(big)19.sp else 16.sp))){when(s){
  S.SPLASH->Splash({go(S.O1)},{go(S.LOGIN)})
  S.O1->Onboard("Cuidado hoje,\nmais liberdade amanhã","O SeniorLink ajuda você a estar sempre por perto, com segurança e praticidade.",1,{go(S.O2)},{go(S.LOGIN)})
  S.O2->Onboard("Localização em\ntempo real","Acompanhe a localização de quem você ama, com segurança e privacidade.",2,{go(S.O3)},{go(S.LOGIN)})
  S.O3->Onboard("Lembretes que\nfazem a diferença","Medicamentos, compromissos e muito mais. Tudo no tempo certo.",3,{go(S.LOGIN)},{go(S.LOGIN)})
  S.LOGIN->Login({e,pwd->if(e==p.getString("email","")&&pwd==p.getString("pwd","")){p.edit().putBoolean("logged",true).apply();go(S.HOME)}},{go(S.CADASTRO)},{p.edit().putBoolean("logged",true).apply();go(S.HOME)})
  S.CADASTRO->Cadastro({go(S.LOGIN)}){n,e,pwd->p.edit().putString("email",e).putString("pwd",pwd).putString("name",n).putBoolean("logged",true).apply();profile=profile.copy(name=n);saveProfile(p,profile);go(S.WELCOME)}
  S.WELCOME->Welcome{go(S.HOME)}
  S.HOME->Home(profile){go(it)}
  S.PERFIL->Profile(profile,{profile=it;saveProfile(p,it);go(S.HOME)},{go(S.HOME)},{go(S.CONTATOS)},{go(S.CONFIG)})
  S.LOCAL->Local({go(S.HOME)},{location.launch(arrayOf(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION))})
  S.LEMBRETES->Lembretes(reminders,{go(S.HOME)},{go(S.NOVO)},{r->val i=reminders.indexOfFirst{it.id==r.id};if(i>=0)reminders[i]=r.copy(active=!r.active);saveReminders(p,reminders)},{r->reminders.removeAll{it.id==r.id};saveReminders(p,reminders)})
  S.NOVO->Novo({go(S.LEMBRETES)}){r->reminders.add(r);saveReminders(p,reminders);schedule(c,r);if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(c,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)notify.launch(Manifest.permission.POST_NOTIFICATIONS);go(S.LEMBRETES)}
  S.SOS->Sos(contacts,{go(S.HOME)},{go(S.CONTATOS)})
  S.APRENDER->Aprender({go(S.HOME)},{go(S.DETALHE)})
  S.DETALHE->Detalhe{go(S.APRENDER)}
  S.CONTATOS->Contatos(contacts,{go(S.HOME)}){l->contacts.clear();contacts.addAll(l);saveContacts(p,contacts)}
  S.CONFIG->Config(big,{big=it;p.edit().putBoolean("big",it).apply()},{go(S.HOME)},{go(S.PERFIL)},{go(S.CONTATOS)},{p.edit().putBoolean("logged",false).apply();go(S.LOGIN)})
 }}
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun Top(t:String,back:()->Unit){TopAppBar(title={Text(t,color=Ink,fontWeight=FontWeight.Bold)},navigationIcon={TextButton(back){Text("‹",fontSize=30.sp,color=Blue)}})}
@Composable fun Splash(start:()->Unit,login:()->Unit){Column(Modifier.fillMaxSize().background(Color.White).padding(26.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.SpaceBetween){Spacer(Modifier.height(20.dp));Column(horizontalAlignment=Alignment.CenterHorizontally){Box(Modifier.size(180.dp).background(Color(0xFFE7F2FC),CircleShape),contentAlignment=Alignment.Center){Text("💚",fontSize=80.sp)};Text("SeniorLink",fontSize=40.sp,fontWeight=FontWeight.ExtraBold,color=Blue);Text("MAIS CONEXÃO PARA TODAS AS FASES DA VIDA",color=Blue,fontWeight=FontWeight.Bold)};Column{Button(start,Modifier.fillMaxWidth().height(55.dp),colors=ButtonDefaults.buttonColors(Teal)){Text("Começar")};TextButton(login,Modifier.fillMaxWidth()){Text("Já tenho uma conta")}}}}
@Composable fun Onboard(t:String,d:String,n:Int,next:()->Unit,skip:()->Unit){Column(Modifier.fillMaxSize().background(Color.White).padding(24.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(45.dp));Box(Modifier.size(245.dp).background(Color(0xFFE7F2FC),CircleShape),contentAlignment=Alignment.Center){Text(if(n==1)"👩‍🦳❤️" else if(n==2)"📍📱" else "🔔",fontSize=72.sp)};Spacer(Modifier.height(35.dp));Text(t,color=Blue,fontSize=28.sp,fontWeight=FontWeight.ExtraBold,textAlign=androidx.compose.ui.text.style.TextAlign.Center);Text(d,color=Ink,fontSize=16.sp,textAlign=androidx.compose.ui.text.style.TextAlign.Center,Modifier.padding(top=14.dp));Spacer(Modifier.weight(1f));Row{repeat(3){Text(if(it==n-1)"●" else "•",color=if(it==n-1)Blue else Color.LightGray,fontSize=20.sp)}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){TextButton(skip){Text("Pular")};Button(next,Modifier.size(58.dp),shape=CircleShape,contentPadding=PaddingValues(0.dp),colors=ButtonDefaults.buttonColors(Teal)){Text("→",fontSize=25.sp)}}}}
@Composable fun Login(onLogin:(String,String)->Unit,register:()->Unit,google:()->Unit){var e by remember{mutableStateOf("")};var pw by remember{mutableStateOf("")};var error by remember{mutableStateOf(false)};Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Text("SeniorLink",color=Blue,fontSize=32.sp,fontWeight=FontWeight.ExtraBold,Modifier.padding(top=30.dp));Text("Bem-vindo de volta!",color=Ink,fontSize=22.sp,fontWeight=FontWeight.Bold);field("E-mail",e){e=it};field("Senha",pw){pw=it};if(error)Text("E-mail ou senha incorretos.",color=Red);Button({onLogin(e,pw);error=true},Modifier.fillMaxWidth().height(54.dp),colors=ButtonDefaults.buttonColors(Teal)){Text("Entrar")};TextButton({}){Text("Esqueceu a senha?")};OutlinedButton(google,Modifier.fillMaxWidth()){Text("Entrar com Google (modo teste)")};OutlinedButton(register,Modifier.fillMaxWidth()){Text("Criar uma conta",color=Teal)}}}
@Composable fun Cadastro(back:()->Unit,save:(String,String,String)->Unit){var n by remember{mutableStateOf("")};var e by remember{mutableStateOf("")};var pw by remember{mutableStateOf("")};var cp by remember{mutableStateOf("")};var err by remember{mutableStateOf("")};Scaffold(topBar={Top("Criar conta",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(18.dp)){field("Nome completo",n){n=it};field("E-mail",e){e=it};field("Senha",pw){pw=it};field("Confirmar senha",cp){cp=it};Text(err,color=Red);Button({if(n.isBlank()||e.isBlank()||pw.isBlank())err="Preencha todos os campos." else if(pw!=cp)err="As senhas não conferem." else save(n,e,pw)},Modifier.fillMaxWidth().height(55.dp),colors=ButtonDefaults.buttonColors(Teal)){Text("Cadastrar")}}}}
@Composable fun field(l:String,v:String,on:(String)->Unit)=OutlinedTextField(v,on,Modifier.fillMaxWidth().padding(vertical=5.dp),label={Text(l)},visualTransformation=if(l.contains("Senha"))PasswordVisualTransformation() else androidx.compose.ui.text.input.VisualTransformation.None)
@Composable fun Welcome(go:()->Unit)=Column(Modifier.fillMaxSize().padding(26.dp),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.Center){Text("🎉",fontSize=70.sp);Text("Tudo pronto!",fontSize=30.sp,fontWeight=FontWeight.Bold,color=Blue);Text("Agora você faz parte do SeniorLink.",color=Ink);Button(go,Modifier.fillMaxWidth().padding(top=25.dp),colors=ButtonDefaults.buttonColors(Teal)){Text("Começar a usar")}}
@Composable fun Home(p:Profile,go:(S)->Unit){Scaffold(containerColor=Bg,bottomBar={NavigationBar{NavigationBarItem(true,{go(S.HOME)},icon={Text("⌂")},label={Text("Início")});NavigationBarItem(false,{go(S.LOCAL)},icon={Text("📍")},label={Text("Localização")});NavigationBarItem(false,{go(S.LEMBRETES)},icon={Text("🔔")},label={Text("Lembretes")});NavigationBarItem(false,{go(S.PERFIL)},icon={Text("👤")},label={Text("Perfil")})}}){pad->LazyColumn(Modifier.fillMaxSize().padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Olá, \${p.name.substringBefore(" ")}! 👋",color=Blue,fontSize=26.sp,fontWeight=FontWeight.ExtraBold);Text("Que bom te ver por aqui!",color=Color.Gray)};item{Row(horizontalArrangement=Arrangement.spacedBy(12.dp)){card("👤","Meu perfil","Seus dados",Color(0xFFE7F2FC),Blue,Modifier.weight(1f)){go(S.PERFIL)};card("📍","Localização","Veja sua localização",Color(0xFFE5F7F3),Teal,Modifier.weight(1f)){go(S.LOCAL)}}};item{Row(horizontalArrangement=Arrangement.spacedBy(12.dp)){card("🔔","Lembretes","Não esqueça do importante",Color(0xFFFFF0DE),Color(0xFFFF9B1C),Modifier.weight(1f)){go(S.LEMBRETES)};card("📚","Aprender","Tutoriais e dicas",Color(0xFFE7F2FC),Blue,Modifier.weight(1f)){go(S.APRENDER)}}};item{Card({go(S.SOS)},Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(Color(0xFFFFE9E9))){Row(Modifier.padding(16.dp),verticalAlignment=Alignment.CenterVertically){Text("🆘",fontSize=30.sp);Spacer(Modifier.width(10.dp));Column{Text("Emergência",color=Red,fontWeight=FontWeight.Bold,fontSize=18.sp);Text("Toque para acionar ajuda",color=Red,fontSize=13.sp)}}}};item{TextButton({go(S.CONFIG)}){Text("⚙ Configurações")}}}}}
@Composable fun RowScope.card(i:String,t:String,d:String,bg:Color,fg:Color,m:Modifier,on:()->Unit){Card(onClick=on,modifier=m.height(125.dp),colors=CardDefaults.cardColors(bg),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(13.dp),verticalArrangement=Arrangement.SpaceBetween){Text(i,fontSize=28.sp);Text(t,color=fg,fontWeight=FontWeight.Bold);Text(d,color=Ink,fontSize=11.sp)}}}
@Composable fun Profile(p:Profile,save:(Profile)->Unit,back:()->Unit,contacts:()->Unit,settings:()->Unit){var n by remember(p){mutableStateOf(p.name)};var b by remember(p){mutableStateOf(p.birth)};var bl by remember(p){mutableStateOf(p.blood)};var a by remember(p){mutableStateOf(p.allergies)};var m by remember(p){mutableStateOf(p.meds)};var co by remember(p){mutableStateOf(p.conditions)};Scaffold(containerColor=Bg,topBar={Top("Meu perfil",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(16.dp)){Text("👩‍🦳",fontSize=80.sp,Modifier.align(Alignment.CenterHorizontally));field("Nome completo",n){n=it};field("Data de nascimento",b){b=it};field("Tipo sanguíneo",bl){bl=it};field("Alergias",a){a=it};field("Medicamentos em uso",m){m=it};field("Condições importantes",co){co=it};Button({save(Profile(n,b,bl,a,m,co))},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(Teal)){Text("Salvar perfil")};OutlinedButton(contacts,Modifier.fillMaxWidth()){Text("Contatos de confiança")};OutlinedButton(settings,Modifier.fillMaxWidth()){Text("Configurações")}}}}
@Composable fun Local(back:()->Unit,request:()->Unit){val c=LocalContext.current;var text by remember{mutableStateOf("Toque em atualizar para obter a localização.")};fun load(){val ok=ContextCompat.checkSelfPermission(c,Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED||ContextCompat.checkSelfPermission(c,Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;if(!ok){request();text="Permissão solicitada. Permita e tente novamente.";return};val lm=c.getSystemService(Context.LOCATION_SERVICE) as LocationManager;val l=lm.getProviders(true).mapNotNull{try{lm.getLastKnownLocation(it)}catch(_:Exception){null}}.minByOrNull{it.accuracy};text=if(l==null)"Localização ainda indisponível." else "Latitude: %.6f\nLongitude: %.6f".format(Locale.US,l.latitude,l.longitude)};Scaffold(containerColor=Bg,topBar={Top("Localização",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).padding(16.dp)){Card(Modifier.fillMaxWidth().height(290.dp),colors=CardDefaults.cardColors(Color(0xFFE7F2FC))){Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("🗺️\n\nMapa do SeniorLink",color=Blue,fontSize=24.sp)}};Text(text,color=Ink,Modifier.padding(16.dp));Button({load()},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(Teal)){Text("Atualizar localização")};OutlinedButton({c.startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("geo:0,0?q=SeniorLink")))},Modifier.fillMaxWidth()){Text("Abrir no mapa")}}};LaunchedEffect(Unit){load()}}
@Composable fun Lembretes(list:List<Reminder>,back:()->Unit,add:()->Unit,toggle:(Reminder)->Unit,del:(Reminder)->Unit){Scaffold(containerColor=Bg,topBar={Top("Meus lembretes",back)},floatingActionButton={FloatingActionButton(add,containerColor=Teal){Text("+",color=Color.White,fontSize=28.sp)}}){pad->if(list.isEmpty())Box(Modifier.fillMaxSize().padding(pad),contentAlignment=Alignment.Center){Text("Nenhum lembrete.\nUse + para adicionar.",color=Ink,textAlign=androidx.compose.ui.text.style.TextAlign.Center)}else LazyColumn(Modifier.fillMaxSize().padding(pad).padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(list){r->Card(Modifier.fillMaxWidth(),colors=CardDefaults.cardColors(Color.White)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Text("🔔",fontSize=25.sp);Column(Modifier.weight(1f)){Text(r.title,color=Ink,fontWeight=FontWeight.Bold);Text(r.desc,color=Color.Gray);Text(SimpleDateFormat("dd/MM/yyyy HH:mm",Locale("pt","BR")).format(Date(r.time)),color=Blue,fontSize=12.sp)};Switch(r.active){toggle(r)};TextButton({del(r)}){Text("Excluir",color=Red)}}}}}}}}
@Composable fun Novo(back:()->Unit,save:(Reminder)->Unit){val c=LocalContext.current;var t by remember{mutableStateOf("")};var d by remember{mutableStateOf("")};var dt by remember{mutableStateOf(Calendar.getInstance().apply{add(Calendar.HOUR,1)})};var repeat by remember{mutableStateOf("Não repetir")};Scaffold(topBar={Top("Novo lembrete",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(16.dp)){field("Título",t){t=it};field("Descrição",d){d=it};Button({DatePickerDialog(c,{_,y,m,day->dt.set(y,m,day)},dt.get(Calendar.YEAR),dt.get(Calendar.MONTH),dt.get(Calendar.DAY_OF_MONTH)).show()},Modifier.fillMaxWidth()){Text("Data: \${SimpleDateFormat("dd/MM/yyyy",Locale("pt","BR")).format(dt.time)}")};Button({TimePickerDialog(c,{_,h,m->dt.set(Calendar.HOUR_OF_DAY,h);dt.set(Calendar.MINUTE,m)},dt.get(Calendar.HOUR_OF_DAY),dt.get(Calendar.MINUTE),true).show()},Modifier.fillMaxWidth()){Text("Horário: \${SimpleDateFormat("HH:mm",Locale("pt","BR")).format(dt.time)}")};Row{listOf("Não repetir","Diariamente").forEach{x->TextButton({repeat=x}){Text(x,color=if(repeat==x)Teal else Blue)}}};Button({if(t.isNotBlank())save(Reminder((System.currentTimeMillis()%Int.MAX_VALUE).toInt(),t,d,dt.timeInMillis,repeat,true))},Modifier.fillMaxWidth(),colors=ButtonDefaults.buttonColors(Teal)){Text("Salvar lembrete")}}}}
@Composable fun Sos(list:List<Contact>,back:()->Unit,contacts:()->Unit){val c=LocalContext.current;val ct=list.firstOrNull();var ask by remember{mutableStateOf(false)};Scaffold(containerColor=Color(0xFFFFE9E9),topBar={Top("Emergência",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).padding(22.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(30.dp));Box(Modifier.size(210.dp).background(Red,CircleShape),contentAlignment=Alignment.Center){Text("☎\nSOS",color=Color.White,fontSize=40.sp,fontWeight=FontWeight.ExtraBold)};Text("Toque para pedir ajuda",color=Red,fontSize=21.sp,fontWeight=FontWeight.Bold,Modifier.padding(20.dp));Text(if(ct==null)"Cadastre um contato de confiança." else "Contato: \${ct.name}",color=Ink);Button({ask=true},Modifier.fillMaxWidth().height(55.dp),colors=ButtonDefaults.buttonColors(Red)){Text("Ligar para contato")};OutlinedButton(contacts,Modifier.fillMaxWidth()){Text("Gerenciar contatos")}}};if(ask)AlertDialog(onDismissRequest={ask=false},title={Text("Confirmar emergência")},text={Text("Abrir o telefone para ligar para \${ct?.name ?: "seu contato"}?")},confirmButton={TextButton({ask=false;ct?.let{c.startActivity(Intent(Intent.ACTION_DIAL,Uri.parse("tel:\${Uri.encode(it.phone)}")))}}){Text("Ligar",color=Red)}},dismissButton={TextButton({ask=false}){Text("Cancelar")}})}}
@Composable fun Aprender(back:()->Unit,open:()->Unit){Scaffold(topBar={Top("Aprender",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).padding(16.dp)){Text("Tutoriais simples para o dia a dia",color=Color.Gray);listOf("📱 Como usar o celular","💬 Como usar o WhatsApp","☎ Como fazer uma ligação","💚 Como usar o SeniorLink","🛡 Dicas de segurança").forEach{x->Card({open()},Modifier.fillMaxWidth().padding(vertical=5.dp)){Text(x,Modifier.padding(18.dp),color=Ink,fontWeight=FontWeight.Bold)}}}}}
@Composable fun Detalhe(back:()->Unit){Scaffold(topBar={Top("Tutorial",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(20.dp)){Text("Como usar o celular",fontSize=26.sp,color=Blue,fontWeight=FontWeight.Bold);listOf("1. Desbloqueie a tela","2. Toque uma vez no aplicativo","3. Use o botão de voltar","4. Peça ajuda quando precisar").forEach{x->Text(x,fontSize=19.sp,color=Ink,Modifier.padding(vertical=12.dp))}}}}
@Composable fun Contatos(list:List<Contact>,back:()->Unit,save:(List<Contact>)->Unit){var show by remember{mutableStateOf(false)};Scaffold(topBar={Top("Meus contatos",back)},floatingActionButton={FloatingActionButton({show=true},containerColor=Teal){Text("+",color=Color.White,fontSize=28.sp)}}){pad->LazyColumn(Modifier.fillMaxSize().padding(pad).padding(12.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){items(list){x->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(x.name,fontWeight=FontWeight.Bold);Text(x.relation);Text(x.phone,color=Blue)};TextButton({cDial(x.phone,LocalContext.current)}){Text("Ligar")};TextButton({save(list.filterNot{it.id==x.id})}){Text("Excluir",color=Red)}}}}}}};if(show)ContactDialog({show=false}){save(list+it);show=false}}
@Composable fun ContactDialog(cancel:()->Unit,ok:(Contact)->Unit){var n by remember{mutableStateOf("")};var ph by remember{mutableStateOf("")};var r by remember{mutableStateOf("")};AlertDialog(onDismissRequest=cancel,title={Text("Adicionar contato")},text={Column{field("Nome",n){n=it};field("Telefone",ph){ph=it};field("Relação",r){r=it}}},confirmButton={TextButton({if(n.isNotBlank()&&ph.isNotBlank())ok(Contact(System.currentTimeMillis(),n,ph,r))}){Text("Salvar",color=Teal)}},dismissButton={TextButton(cancel){Text("Cancelar")}})}
@Composable fun Config(big:Boolean,bigChange:(Boolean)->Unit,back:()->Unit,profile:()->Unit,contacts:()->Unit,logout:()->Unit){Scaffold(topBar={Top("Configurações",back)}){pad->Column(Modifier.fillMaxSize().padding(pad).padding(16.dp)){setting("👤","Minha conta",profile);Row(Modifier.fillMaxWidth().padding(10.dp),verticalAlignment=Alignment.CenterVertically){Text("♿ Texto maior",Modifier.weight(1f));Switch(big,bigChange)};setting("☎","Contatos de confiança",contacts);setting("ℹ","Sobre o app"){};OutlinedButton(logout,Modifier.fillMaxWidth()){Text("Sair da conta",color=Red)}}}}
@Composable fun setting(i:String,t:String,on:()->Unit){Card(onClick=on,Modifier.fillMaxWidth().padding(5.dp)){Row(Modifier.padding(16.dp)){Text(i,fontSize=22.sp);Spacer(Modifier.width(10.dp));Text(t,color=Ink,fontWeight=FontWeight.Bold)}}}
fun cDial(phone:String,c:Context){c.startActivity(Intent(Intent.ACTION_DIAL,Uri.parse("tel:\${Uri.encode(phone)}")))}
fun loadProfile(p:SharedPreferences)=Profile(p.getString("profile",null) ?: p.getString("name","Maria Silva de Oliveira").orEmpty())
fun saveProfile(p:SharedPreferences,x:Profile){p.edit().putString("profile",x.name).apply()}
fun loadContacts(p:SharedPreferences):List<Contact>{val a=JSONArray(p.getString("contacts","[]")!!);return buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(Contact(o.getLong("id"),o.getString("name"),o.getString("phone"),o.optString("relation")))}}}
fun saveContacts(p:SharedPreferences,l:List<Contact>){val a=JSONArray();l.forEach{x->a.put(JSONObject().apply{put("id",x.id);put("name",x.name);put("phone",x.phone);put("relation",x.relation)})};p.edit().putString("contacts",a.toString()).apply()}
fun loadReminders(p:SharedPreferences):List<Reminder>{val a=JSONArray(p.getString("reminders","[]")!!);return buildList{for(i in 0 until a.length()){val o=a.getJSONObject(i);add(Reminder(o.getInt("id"),o.getString("title"),o.optString("desc"),o.getLong("time"),o.optString("repeat"),o.optBoolean("active",true)))}}}
fun saveReminders(p:SharedPreferences,l:List<Reminder>){val a=JSONArray();l.forEach{x->a.put(JSONObject().apply{put("id",x.id);put("title",x.title);put("desc",x.desc);put("time",x.time);put("repeat",x.repeat);put("active",x.active)})};p.edit().putString("reminders",a.toString()).apply()}
fun schedule(c:Context,r:Reminder){val i=Intent(c,ReminderReceiver::class.java).apply{putExtra("id",r.id);putExtra("title",r.title);putExtra("desc",r.desc)};val pi=PendingIntent.getBroadcast(c,r.id,i,PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE);(c.getSystemService(Context.ALARM_SERVICE) as AlarmManager).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,r.time,pi)}
